name: Require Checklist
description: Ensure that any checklists in an issue/pull request are completed
runs:
  using: node20
  main: dist/index.js
branding:
  icon: check-square
  color: gray-dark
inputs:
  token:
    description: The GitHub API token to use
    default: ${{ github.token }}
    required: false
  requireChecklist:
    description: Require a checklist to exist
    required: false
    default: 'false'
  skipComments:
    description: Do not look for checklists in comments
    required: false
    default: 'false'
  skipDescriptionRegex:
    description: A regex pattern of descriptions that will be skipped if matched
    required: false
    default: undefined
