name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
